[server]
host = "127.0.0.1"
port = 10110

[scheduler]
interval = 5
agentContactDelay = 30

[agent]
ipAddresses = "127.0.0.1"

[auth]
type = "header"

# type = "jwt"
# key = "secret"

[etcd]
address = "http://127.0.0.1:2379"

[elasticsearch]
address = "http://127.0.0.1:9200"
