version: 2
jobs:
  lint:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla-server
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - run: apt update
      - run: apt install -y golang-glide protobuf-compiler golang-protobuf-extensions-dev
      - run: make deps
      - run: go fmt $(go list ./... | grep -v /vendor/)
      - run: go vet $(go list ./... | grep -v /vendor/)
      - run: go test -race $(go list ./... | grep -v /vendor/)

  build:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla-server
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - run: apt update
      - run: apt install -y golang-glide protobuf-compiler golang-protobuf-extensions-dev zip
      - run: make deps
      - run: make release
      - store_artifacts:
          path: chinchilla-server.zip
          destination: chinchilla-server.zip

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build:
          requires:
            - lint