version: 2.1
jobs:
  lint:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla-server
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - run:
          command: |
            apt update
            apt install -y golang-glide
            make deps
      - run:
          command: |
            go fmt $(go list ./... | grep -v /vendor/)
            go vet $(go list ./... | grep -v /vendor/)
            go test -race $(go list ./... | grep -v /vendor/)
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  build:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla-server
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            apt update
            apt install -y golang-glide zip
      - run:
          command: SERVER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1} make release
      - store_artifacts:
          path: release/chinchilla-server.zip
          destination: chinchilla-server.zip
      - persist_to_workspace:
          root: .
          paths:
            - release

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_TAG
            ghr -t ${GITHUB_TOKEN} -replace ${VERSION} release

workflows:
  version: 2
  lint_build_release:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/