version: 2.1
jobs:
  lint:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - run:
          command: |
            apt update
            apt install -y golang-glide
            make deps
      - run:
          command: |
            go fmt $(go list ./... | grep -v /vendor/)
            go vet $(go list ./... | grep -v /vendor/)
            go test -race $(go list ./... | grep -v /vendor/)
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  build:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            apt update
            apt install -y golang-glide zip protobuf-compiler golang-goprotobuf-dev
      - run:
          command: VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1} make release
      - store_artifacts:
          path: release/chinchilla.zip
          destination: chinchilla.zip
      - persist_to_workspace:
          root: .
          paths:
            - release

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} release

  build-docker:
    docker:
      - image: docker
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: "Build docker images"
          command: |
            docker build -f docker/server/Dockerfile -t trojan295/chinchilla-server .
            docker build -f docker/scheduler/Dockerfile -t trojan295/chinchilla-scheduler .
            docker build -f docker/agent/Dockerfile -t trojan295/chinchilla-agent .

  publish-dockerhub-image:
    docker:
      - image: docker
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker build -f docker/server/Dockerfile -t trojan295/chinchilla-server:${CIRCLE_TAG:-$CIRLCE_BRANCH} .
            docker build -f docker/scheduler/Dockerfile -t trojan295/chinchilla-scheduler:${CIRCLE_TAG:-$CIRLCE_BRANCH} .
            docker build -f docker/agent/Dockerfile -t trojan295/chinchilla-agent:${CIRCLE_TAG:-$CIRLCE_BRANCH} .
            docker push trojan295/chinchilla-server:${CIRCLE_TAG:-$CIRLCE_BRANCH}
            docker push trojan295/chinchilla-scheduler:${CIRCLE_TAG:-$CIRLCE_BRANCH}
            docker push trojan295/chinchilla-agent:${CIRCLE_TAG:-$CIRLCE_BRANCH}

workflows:
  version: 2
  lint_build_release:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/

      - build:
          requires:
            - lint
          filters:
            tags:
              only: /.*/

      - publish-github-release:
          requires:
            - build
          context: Github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

      - build-docker:
          requires:
            - lint
          filters:
            tags:
              only: /.*/

      - publish-dockerhub-image:
          requires:
            - build-docker
          context: Dockerhub
          filters:
            branches:
              only: master
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
