version: 2.1
jobs:
  lint:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla-server
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - run:
          command: |
            apt update
            apt install -y golang-glide
            make deps
      - run:
          command: |
            go fmt $(go list ./... | grep -v /vendor/)
            go vet $(go list ./... | grep -v /vendor/)
            go test -race $(go list ./... | grep -v /vendor/)
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  build:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/Trojan295/chinchilla-server
    steps:
      - add_ssh_keys:
          fingerprints:
          - "cf:b1:dd:8d:15:5a:8e:3e:1b:24:f4:d3:19:bc:01:93"
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            apt update
            apt install -y golang-glide zip
            export SERVER_VERSION=$CIRCLE_CI >> $BASH_ENV
      - run:
          command: make release
      - store_artifacts:
          path: chinchilla-server.zip
          destination: chinchilla-server.zip

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build:
          requires:
            - lint