// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/agent.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameserverStatus int32

const (
	GameserverStatus_RUNNING GameserverStatus = 0
	GameserverStatus_PENDING GameserverStatus = 1
	GameserverStatus_ERROR   GameserverStatus = 2
)

var GameserverStatus_name = map[int32]string{
	0: "RUNNING",
	1: "PENDING",
	2: "ERROR",
}

var GameserverStatus_value = map[string]int32{
	"RUNNING": 0,
	"PENDING": 1,
	"ERROR":   2,
}

func (x GameserverStatus) String() string {
	return proto.EnumName(GameserverStatus_name, int32(x))
}

func (GameserverStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{0}
}

type NetworkProtocol int32

const (
	NetworkProtocol_TCP NetworkProtocol = 0
	NetworkProtocol_UDP NetworkProtocol = 1
)

var NetworkProtocol_name = map[int32]string{
	0: "TCP",
	1: "UDP",
}

var NetworkProtocol_value = map[string]int32{
	"TCP": 0,
	"UDP": 1,
}

func (x NetworkProtocol) String() string {
	return proto.EnumName(NetworkProtocol_name, int32(x))
}

func (NetworkProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{1}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AgentResources struct {
	Cpus                 int64    `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory               int64    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	IpAddresses          int64    `protobuf:"varint,3,opt,name=ipAddresses,proto3" json:"ipAddresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentResources) Reset()         { *m = AgentResources{} }
func (m *AgentResources) String() string { return proto.CompactTextString(m) }
func (*AgentResources) ProtoMessage()    {}
func (*AgentResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{1}
}

func (m *AgentResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentResources.Unmarshal(m, b)
}
func (m *AgentResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentResources.Marshal(b, m, deterministic)
}
func (m *AgentResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentResources.Merge(m, src)
}
func (m *AgentResources) XXX_Size() int {
	return xxx_messageInfo_AgentResources.Size(m)
}
func (m *AgentResources) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentResources.DiscardUnknown(m)
}

var xxx_messageInfo_AgentResources proto.InternalMessageInfo

func (m *AgentResources) GetCpus() int64 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *AgentResources) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *AgentResources) GetIpAddresses() int64 {
	if m != nil {
		return m.IpAddresses
	}
	return 0
}

type AgentResourceUsage struct {
	Memory               int64    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentResourceUsage) Reset()         { *m = AgentResourceUsage{} }
func (m *AgentResourceUsage) String() string { return proto.CompactTextString(m) }
func (*AgentResourceUsage) ProtoMessage()    {}
func (*AgentResourceUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{2}
}

func (m *AgentResourceUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentResourceUsage.Unmarshal(m, b)
}
func (m *AgentResourceUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentResourceUsage.Marshal(b, m, deterministic)
}
func (m *AgentResourceUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentResourceUsage.Merge(m, src)
}
func (m *AgentResourceUsage) XXX_Size() int {
	return xxx_messageInfo_AgentResourceUsage.Size(m)
}
func (m *AgentResourceUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentResourceUsage.DiscardUnknown(m)
}

var xxx_messageInfo_AgentResourceUsage proto.InternalMessageInfo

func (m *AgentResourceUsage) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type AgentState struct {
	Hostname             string              `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Resources            *AgentResources     `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	ResourceUsage        *AgentResourceUsage `protobuf:"bytes,3,opt,name=resourceUsage,proto3" json:"resourceUsage,omitempty"`
	RunningGameservers   []*Gameserver       `protobuf:"bytes,4,rep,name=runningGameservers,proto3" json:"runningGameservers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AgentState) Reset()         { *m = AgentState{} }
func (m *AgentState) String() string { return proto.CompactTextString(m) }
func (*AgentState) ProtoMessage()    {}
func (*AgentState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{3}
}

func (m *AgentState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentState.Unmarshal(m, b)
}
func (m *AgentState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentState.Marshal(b, m, deterministic)
}
func (m *AgentState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentState.Merge(m, src)
}
func (m *AgentState) XXX_Size() int {
	return xxx_messageInfo_AgentState.Size(m)
}
func (m *AgentState) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentState.DiscardUnknown(m)
}

var xxx_messageInfo_AgentState proto.InternalMessageInfo

func (m *AgentState) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentState) GetResources() *AgentResources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *AgentState) GetResourceUsage() *AgentResourceUsage {
	if m != nil {
		return m.ResourceUsage
	}
	return nil
}

func (m *AgentState) GetRunningGameservers() []*Gameserver {
	if m != nil {
		return m.RunningGameservers
	}
	return nil
}

type Endpoint struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{4}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type Gameserver struct {
	UUID                 string           `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Status               GameserverStatus `protobuf:"varint,2,opt,name=status,proto3,enum=proto.GameserverStatus" json:"status,omitempty"`
	Info                 string           `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Endpoint             *Endpoint        `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Gameserver) Reset()         { *m = Gameserver{} }
func (m *Gameserver) String() string { return proto.CompactTextString(m) }
func (*Gameserver) ProtoMessage()    {}
func (*Gameserver) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{5}
}

func (m *Gameserver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gameserver.Unmarshal(m, b)
}
func (m *Gameserver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gameserver.Marshal(b, m, deterministic)
}
func (m *Gameserver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gameserver.Merge(m, src)
}
func (m *Gameserver) XXX_Size() int {
	return xxx_messageInfo_Gameserver.Size(m)
}
func (m *Gameserver) XXX_DiscardUnknown() {
	xxx_messageInfo_Gameserver.DiscardUnknown(m)
}

var xxx_messageInfo_Gameserver proto.InternalMessageInfo

func (m *Gameserver) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Gameserver) GetStatus() GameserverStatus {
	if m != nil {
		return m.Status
	}
	return GameserverStatus_RUNNING
}

func (m *Gameserver) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Gameserver) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type GetGameserverDeploymentsRequest struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameserverDeploymentsRequest) Reset()         { *m = GetGameserverDeploymentsRequest{} }
func (m *GetGameserverDeploymentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGameserverDeploymentsRequest) ProtoMessage()    {}
func (*GetGameserverDeploymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{6}
}

func (m *GetGameserverDeploymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameserverDeploymentsRequest.Unmarshal(m, b)
}
func (m *GetGameserverDeploymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameserverDeploymentsRequest.Marshal(b, m, deterministic)
}
func (m *GetGameserverDeploymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameserverDeploymentsRequest.Merge(m, src)
}
func (m *GetGameserverDeploymentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGameserverDeploymentsRequest.Size(m)
}
func (m *GetGameserverDeploymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameserverDeploymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameserverDeploymentsRequest proto.InternalMessageInfo

func (m *GetGameserverDeploymentsRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type ResourceRequirements struct {
	CpuReservation       int64    `protobuf:"varint,1,opt,name=cpuReservation,proto3" json:"cpuReservation,omitempty"`
	CpuLimit             int64    `protobuf:"varint,2,opt,name=cpuLimit,proto3" json:"cpuLimit,omitempty"`
	MemoryReservation    int64    `protobuf:"varint,3,opt,name=memoryReservation,proto3" json:"memoryReservation,omitempty"`
	MemoryLimit          int64    `protobuf:"varint,4,opt,name=memoryLimit,proto3" json:"memoryLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceRequirements) Reset()         { *m = ResourceRequirements{} }
func (m *ResourceRequirements) String() string { return proto.CompactTextString(m) }
func (*ResourceRequirements) ProtoMessage()    {}
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{7}
}

func (m *ResourceRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRequirements.Unmarshal(m, b)
}
func (m *ResourceRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRequirements.Marshal(b, m, deterministic)
}
func (m *ResourceRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRequirements.Merge(m, src)
}
func (m *ResourceRequirements) XXX_Size() int {
	return xxx_messageInfo_ResourceRequirements.Size(m)
}
func (m *ResourceRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRequirements proto.InternalMessageInfo

func (m *ResourceRequirements) GetCpuReservation() int64 {
	if m != nil {
		return m.CpuReservation
	}
	return 0
}

func (m *ResourceRequirements) GetCpuLimit() int64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *ResourceRequirements) GetMemoryReservation() int64 {
	if m != nil {
		return m.MemoryReservation
	}
	return 0
}

func (m *ResourceRequirements) GetMemoryLimit() int64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

type NetworkPort struct {
	Protocol             NetworkProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=proto.NetworkProtocol" json:"protocol,omitempty"`
	ContainerPort        int64           `protobuf:"varint,2,opt,name=containerPort,proto3" json:"containerPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NetworkPort) Reset()         { *m = NetworkPort{} }
func (m *NetworkPort) String() string { return proto.CompactTextString(m) }
func (*NetworkPort) ProtoMessage()    {}
func (*NetworkPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{8}
}

func (m *NetworkPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPort.Unmarshal(m, b)
}
func (m *NetworkPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPort.Marshal(b, m, deterministic)
}
func (m *NetworkPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPort.Merge(m, src)
}
func (m *NetworkPort) XXX_Size() int {
	return xxx_messageInfo_NetworkPort.Size(m)
}
func (m *NetworkPort) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPort.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPort proto.InternalMessageInfo

func (m *NetworkPort) GetProtocol() NetworkProtocol {
	if m != nil {
		return m.Protocol
	}
	return NetworkProtocol_TCP
}

func (m *NetworkPort) GetContainerPort() int64 {
	if m != nil {
		return m.ContainerPort
	}
	return 0
}

type EnvironmentVariable struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvironmentVariable) Reset()         { *m = EnvironmentVariable{} }
func (m *EnvironmentVariable) String() string { return proto.CompactTextString(m) }
func (*EnvironmentVariable) ProtoMessage()    {}
func (*EnvironmentVariable) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{9}
}

func (m *EnvironmentVariable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentVariable.Unmarshal(m, b)
}
func (m *EnvironmentVariable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentVariable.Marshal(b, m, deterministic)
}
func (m *EnvironmentVariable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentVariable.Merge(m, src)
}
func (m *EnvironmentVariable) XXX_Size() int {
	return xxx_messageInfo_EnvironmentVariable.Size(m)
}
func (m *EnvironmentVariable) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentVariable.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentVariable proto.InternalMessageInfo

func (m *EnvironmentVariable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvironmentVariable) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GameserverDeployment struct {
	UUID                 string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Agent                string                 `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Image                string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ResourceRequirements *ResourceRequirements  `protobuf:"bytes,5,opt,name=resourceRequirements,proto3" json:"resourceRequirements,omitempty"`
	Ports                []*NetworkPort         `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	Environment          []*EnvironmentVariable `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GameserverDeployment) Reset()         { *m = GameserverDeployment{} }
func (m *GameserverDeployment) String() string { return proto.CompactTextString(m) }
func (*GameserverDeployment) ProtoMessage()    {}
func (*GameserverDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{10}
}

func (m *GameserverDeployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameserverDeployment.Unmarshal(m, b)
}
func (m *GameserverDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameserverDeployment.Marshal(b, m, deterministic)
}
func (m *GameserverDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameserverDeployment.Merge(m, src)
}
func (m *GameserverDeployment) XXX_Size() int {
	return xxx_messageInfo_GameserverDeployment.Size(m)
}
func (m *GameserverDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_GameserverDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_GameserverDeployment proto.InternalMessageInfo

func (m *GameserverDeployment) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *GameserverDeployment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameserverDeployment) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *GameserverDeployment) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *GameserverDeployment) GetResourceRequirements() *ResourceRequirements {
	if m != nil {
		return m.ResourceRequirements
	}
	return nil
}

func (m *GameserverDeployment) GetPorts() []*NetworkPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *GameserverDeployment) GetEnvironment() []*EnvironmentVariable {
	if m != nil {
		return m.Environment
	}
	return nil
}

type GetGameserverDeploymentsResponse struct {
	Deployments          []*GameserverDeployment `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetGameserverDeploymentsResponse) Reset()         { *m = GetGameserverDeploymentsResponse{} }
func (m *GetGameserverDeploymentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetGameserverDeploymentsResponse) ProtoMessage()    {}
func (*GetGameserverDeploymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{11}
}

func (m *GetGameserverDeploymentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameserverDeploymentsResponse.Unmarshal(m, b)
}
func (m *GetGameserverDeploymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameserverDeploymentsResponse.Marshal(b, m, deterministic)
}
func (m *GetGameserverDeploymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameserverDeploymentsResponse.Merge(m, src)
}
func (m *GetGameserverDeploymentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetGameserverDeploymentsResponse.Size(m)
}
func (m *GetGameserverDeploymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameserverDeploymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameserverDeploymentsResponse proto.InternalMessageInfo

func (m *GetGameserverDeploymentsResponse) GetDeployments() []*GameserverDeployment {
	if m != nil {
		return m.Deployments
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.GameserverStatus", GameserverStatus_name, GameserverStatus_value)
	proto.RegisterEnum("proto.NetworkProtocol", NetworkProtocol_name, NetworkProtocol_value)
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*AgentResources)(nil), "proto.AgentResources")
	proto.RegisterType((*AgentResourceUsage)(nil), "proto.AgentResourceUsage")
	proto.RegisterType((*AgentState)(nil), "proto.AgentState")
	proto.RegisterType((*Endpoint)(nil), "proto.Endpoint")
	proto.RegisterType((*Gameserver)(nil), "proto.Gameserver")
	proto.RegisterType((*GetGameserverDeploymentsRequest)(nil), "proto.GetGameserverDeploymentsRequest")
	proto.RegisterType((*ResourceRequirements)(nil), "proto.ResourceRequirements")
	proto.RegisterType((*NetworkPort)(nil), "proto.NetworkPort")
	proto.RegisterType((*EnvironmentVariable)(nil), "proto.EnvironmentVariable")
	proto.RegisterType((*GameserverDeployment)(nil), "proto.GameserverDeployment")
	proto.RegisterType((*GetGameserverDeploymentsResponse)(nil), "proto.GetGameserverDeploymentsResponse")
}

func init() { proto.RegisterFile("proto/agent.proto", fileDescriptor_dd830a99d5efef4e) }

var fileDescriptor_dd830a99d5efef4e = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x8d, 0x7c, 0xf7, 0x28, 0x71, 0xec, 0x59, 0x6f, 0x56, 0xeb, 0x2c, 0xb0, 0x86, 0x76, 0x91,
	0x1a, 0x69, 0x90, 0x00, 0xce, 0x43, 0x5f, 0x1a, 0x04, 0x41, 0x6d, 0x04, 0x01, 0x0a, 0xc7, 0x60,
	0xea, 0x3e, 0x16, 0x50, 0x6c, 0xd6, 0x15, 0x62, 0x91, 0x2a, 0x49, 0xb9, 0xc8, 0x6f, 0xf4, 0x17,
	0xfa, 0x52, 0xf4, 0xaf, 0xfa, 0x27, 0x05, 0x29, 0xd9, 0x92, 0x2f, 0x49, 0x9f, 0xc4, 0x19, 0x1e,
	0x1e, 0x0d, 0xcf, 0x9c, 0x21, 0x34, 0x42, 0xc1, 0x15, 0x3f, 0xf3, 0xa6, 0x94, 0xa9, 0x53, 0xb3,
	0xc6, 0xa2, 0xf9, 0xb8, 0x65, 0x28, 0xf6, 0x83, 0x50, 0x3d, 0xba, 0x1f, 0xa0, 0x76, 0xa5, 0xb7,
	0x09, 0x95, 0x3c, 0x12, 0x63, 0x2a, 0x11, 0xa1, 0x30, 0x0e, 0x23, 0xe9, 0x58, 0x6d, 0xab, 0x93,
	0x27, 0x66, 0x8d, 0x07, 0x50, 0x0a, 0x68, 0xc0, 0xc5, 0xa3, 0x93, 0x33, 0xd9, 0x24, 0xc2, 0x36,
	0xd8, 0x7e, 0x78, 0x35, 0x99, 0x08, 0x2a, 0x25, 0x95, 0x4e, 0xde, 0x6c, 0x66, 0x53, 0xee, 0x09,
	0xe0, 0x0a, 0xff, 0x48, 0x7a, 0x53, 0xfa, 0x14, 0x9f, 0xfb, 0xd3, 0x02, 0x30, 0xf0, 0x3b, 0xe5,
	0x29, 0x8a, 0x2d, 0xa8, 0x7c, 0xe2, 0x52, 0x31, 0x2f, 0xa0, 0xa6, 0x9c, 0x2a, 0x59, 0xc6, 0x78,
	0x0e, 0x55, 0xb1, 0xa8, 0xd9, 0xb0, 0xd8, 0xdd, 0x3f, 0xe3, 0x3b, 0x9e, 0xae, 0x5e, 0x88, 0xa4,
	0x38, 0xbc, 0x84, 0x3d, 0x91, 0x2d, 0xc4, 0x54, 0x6c, 0x77, 0xff, 0xde, 0x76, 0xd0, 0x00, 0xc8,
	0x2a, 0x1e, 0xaf, 0x00, 0x45, 0xc4, 0x98, 0xcf, 0xa6, 0xd7, 0x5e, 0x40, 0x25, 0x15, 0x73, 0x2a,
	0xa4, 0x53, 0x68, 0xe7, 0x3b, 0x76, 0xb7, 0x91, 0xb0, 0xa4, 0x3b, 0x64, 0x0b, 0xd8, 0xed, 0x40,
	0xa5, 0xcf, 0x26, 0x21, 0xf7, 0x99, 0xc2, 0x7f, 0xa0, 0xba, 0x14, 0x2b, 0xb9, 0x61, 0x9a, 0x70,
	0xbf, 0x5a, 0x00, 0xe9, 0x49, 0xdd, 0x98, 0xd1, 0xe8, 0xa6, 0x97, 0xe0, 0xcc, 0x1a, 0xcf, 0xa0,
	0x24, 0x95, 0xa7, 0xa2, 0x58, 0x82, 0x5a, 0xf7, 0xaf, 0x8d, 0x1a, 0xee, 0xcc, 0x36, 0x49, 0x60,
	0x9a, 0xc4, 0x67, 0x1f, 0xb9, 0xb9, 0x78, 0x95, 0x98, 0x35, 0xbe, 0x84, 0x0a, 0x4d, 0x2a, 0x72,
	0x0a, 0x46, 0x90, 0xfd, 0x84, 0x66, 0x51, 0x28, 0x59, 0x02, 0xdc, 0x0b, 0xf8, 0xf7, 0x9a, 0xaa,
	0x94, 0xbf, 0x47, 0xc3, 0x19, 0x7f, 0x0c, 0x28, 0x53, 0x92, 0xd0, 0xcf, 0x11, 0x95, 0xea, 0xb9,
	0xb6, 0xb9, 0x3f, 0x2c, 0x68, 0x2e, 0x14, 0xd6, 0x78, 0x5f, 0x50, 0x73, 0x16, 0x8f, 0xa0, 0x36,
	0x0e, 0x23, 0x62, 0x58, 0x3d, 0xe5, 0x73, 0x96, 0x18, 0x70, 0x2d, 0xab, 0xc9, 0xc7, 0x61, 0xf4,
	0xd6, 0x0f, 0x7c, 0x95, 0x98, 0x67, 0x19, 0xe3, 0x09, 0x34, 0x62, 0x23, 0x65, 0x69, 0x62, 0x53,
	0x6e, 0x6e, 0x68, 0xf3, 0xc6, 0xc9, 0x98, 0xac, 0x10, 0x9b, 0x37, 0x93, 0x72, 0xa7, 0x60, 0x0f,
	0xa8, 0xfa, 0xc2, 0xc5, 0xc3, 0x90, 0x0b, 0x85, 0x5d, 0xa8, 0x18, 0x59, 0xc6, 0x7c, 0x66, 0x8a,
	0xab, 0x75, 0x0f, 0x12, 0x9d, 0x16, 0xa8, 0x64, 0x97, 0x2c, 0x71, 0xf8, 0x3f, 0xec, 0x8d, 0x39,
	0x53, 0x9e, 0xcf, 0xa8, 0xd0, 0x24, 0x49, 0xcd, 0xab, 0x49, 0xf7, 0x12, 0xfe, 0xe8, 0xb3, 0xb9,
	0x2f, 0x38, 0xd3, 0x62, 0xbc, 0xf7, 0x84, 0xef, 0xdd, 0xcf, 0xa8, 0x6e, 0x56, 0x46, 0x44, 0xb3,
	0xc6, 0x26, 0x14, 0xe7, 0xde, 0x2c, 0xa2, 0x86, 0xa8, 0x4a, 0xe2, 0xc0, 0xfd, 0x96, 0x83, 0xe6,
	0xb6, 0x9e, 0x6c, 0x35, 0xcd, 0x82, 0x36, 0xb7, 0x4a, 0x6b, 0x9e, 0x89, 0xc4, 0x18, 0x71, 0xa0,
	0xb3, 0x7e, 0xa0, 0xe7, 0xa4, 0x10, 0x67, 0x4d, 0x80, 0xb7, 0xd0, 0x14, 0x5b, 0x5a, 0xe8, 0x14,
	0x8d, 0x77, 0x0e, 0x13, 0x4d, 0xb6, 0x75, 0x99, 0x6c, 0x3d, 0x88, 0x1d, 0x28, 0x86, 0x5c, 0x28,
	0xe9, 0x94, 0xcc, 0x20, 0xe1, 0x9a, 0xaa, 0x5c, 0x28, 0x12, 0x03, 0xf0, 0x35, 0xd8, 0x34, 0x15,
	0xca, 0x29, 0x1b, 0x7c, 0x6b, 0xe9, 0xd6, 0x0d, 0x09, 0x49, 0x16, 0xee, 0x7a, 0xd0, 0x7e, 0xda,
	0xbb, 0x32, 0xe4, 0x4c, 0x52, 0xbc, 0x00, 0x7b, 0x92, 0xa6, 0x1d, 0xcb, 0xfc, 0xe1, 0x70, 0x63,
	0xac, 0xd2, 0xa3, 0x24, 0x8b, 0x3f, 0x7e, 0x05, 0xf5, 0xf5, 0xd9, 0x43, 0x1b, 0xca, 0x64, 0x34,
	0x18, 0xdc, 0x0c, 0xae, 0xeb, 0x3b, 0x3a, 0x18, 0xf6, 0x07, 0x3d, 0x1d, 0x58, 0x58, 0x85, 0x62,
	0x9f, 0x90, 0x5b, 0x52, 0xcf, 0x1d, 0xff, 0x07, 0xfb, 0x6b, 0x2e, 0xc2, 0x32, 0xe4, 0xdf, 0xbd,
	0x19, 0xd6, 0x77, 0xf4, 0x62, 0xd4, 0x1b, 0xd6, 0xad, 0xee, 0x77, 0x0b, 0x76, 0xe3, 0xf7, 0x91,
	0x8a, 0xb9, 0x3f, 0xa6, 0x7a, 0x74, 0x09, 0x9d, 0xfa, 0x52, 0x51, 0x81, 0x8d, 0xec, 0x2b, 0x66,
	0x1e, 0xd0, 0xd6, 0xee, 0x42, 0x19, 0xfd, 0xd6, 0xe3, 0x03, 0x38, 0x4f, 0x5d, 0x1f, 0x8f, 0x16,
	0x37, 0x7c, 0x7e, 0xb6, 0x5b, 0x2f, 0x7e, 0x8b, 0x8b, 0x75, 0xbc, 0x2f, 0x19, 0xdc, 0xf9, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xcc, 0xc0, 0x2d, 0x84, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	Register(ctx context.Context, in *AgentState, opts ...grpc.CallOption) (*Empty, error)
	GetGameserverDeployments(ctx context.Context, in *GetGameserverDeploymentsRequest, opts ...grpc.CallOption) (*GetGameserverDeploymentsResponse, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *AgentState, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.AgentService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetGameserverDeployments(ctx context.Context, in *GetGameserverDeploymentsRequest, opts ...grpc.CallOption) (*GetGameserverDeploymentsResponse, error) {
	out := new(GetGameserverDeploymentsResponse)
	err := c.cc.Invoke(ctx, "/proto.AgentService/GetGameserverDeployments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	Register(context.Context, *AgentState) (*Empty, error)
	GetGameserverDeployments(context.Context, *GetGameserverDeploymentsRequest) (*GetGameserverDeploymentsResponse, error)
}

// UnimplementedAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (*UnimplementedAgentServiceServer) Register(ctx context.Context, req *AgentState) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAgentServiceServer) GetGameserverDeployments(ctx context.Context, req *GetGameserverDeploymentsRequest) (*GetGameserverDeploymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameserverDeployments not implemented")
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*AgentState))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetGameserverDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameserverDeploymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetGameserverDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/GetGameserverDeployments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetGameserverDeployments(ctx, req.(*GetGameserverDeploymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "GetGameserverDeployments",
			Handler:    _AgentService_GetGameserverDeployments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent.proto",
}
